=== AntonSorokin1/XML_and_JSON/src/main/resources/xml/xsd/SomeShopSchema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="https://www.cs.com/">
    <xs:element name="shop">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="categories">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="kitchen">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="technique" type="subcategory"/>
                                        <xs:element name="hardware" type="subcategory"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="bedroom">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="technique" type="subcategory"/>
                                        <xs:element name="hardware" type="subcategory"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="livingRoom">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="technique" type="subcategory"/>
                                        <xs:element name="hardware" type="subcategory"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>


    <xs:complexType name="subcategory">
        <xs:sequence>
            <xs:element name="product" type="product"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="product">
        <xs:attribute name="manufacturer" type="xs:string"/>
        <xs:attribute name="model"        type="model"/>
        <xs:attribute name="date"         type="xs:string"/>
        <xs:attribute name="color"        type="xs:string"/>
        <xs:attribute name="price"        type="xs:double"/>
        <xs:attribute name="number"       type="xs:integer"/>
        <xs:attribute name="isAvailable"  type="xs:boolean"/>
    </xs:complexType>

    <xs:complexType name="model">
        <xs:attribute name="batch" type="xs:string"/>
        <xs:attribute name="number" type="xs:integer"/>
    </xs:complexType>
</xs:schema>

=== AntonSorokin1/XML_and_JSON/resources/xml/SomeShop.xml
<?xml version="1.0" encoding="UTF-8"?>
<cs:shop xmlns:cs="https://www.cs.com/" xmlns:xs="http://www.w3.org/2001/XMLSchema-instance" xs:schemaLocation="https://www.cs.com/ xsd/SomeShopSchema.xsd">
    <categories>
        <kitchen>
            <technique>
                <product manufacturer="BIRUSA" model="AB123" date="31-12-2020" color="Red"   price="100.10" number="0" isAvailable="false"/>
                <product manufacturer="BIRUSA" model="AC123" date="30-12-2020" color="Green" price="100.20" number="15" isAvailable="true"/>
                <product manufacturer="BIRUSA" model="AD123" date="29-12-2020" color="Blue"  price="100.30" number="0" isAvailable="false"/>
            </technique>
            <hardware>
                <product manufacturer="DRUZHBA" model="AE234" date="28-11-2020" color="Red"   price="200.40" number="20" isAvailable="true"/>
                <product manufacturer="DRUZHBA" model="AF234" date="27-11-2020" color="Green" price="200.50" number="0" isAvailable="false"/>
                <product manufacturer="DRUZHBA" model="AG234" date="26-11-2020" color="Blue"  price="200.60" number="21" isAvailable="true"/>
            </hardware>
        </kitchen>
        <bedroom>
            <technique>
                <product manufacturer="BOSH" model="BC345" date="25-10-2019" color="Red"   price="1100.10" number="5" isAvailable="true"/>
                <product manufacturer="BOSH" model="BD345" date="24-10-2019" color="Green" price="1100.20" number="0" isAvailable="false"/>
                <product manufacturer="BOSH" model="BE345" date="23-10-2019" color="Blue"  price="1100.30" number="3" isAvailable="true"/>
            </technique>
            <hardware>
                <product manufacturer="SHELLY" model="BF456" date="22-09-2019" color="Red"   price="1200.40" number="6" isAvailable="true"/>
                <product manufacturer="SHELLY" model="BG456" date="21-09-2019" color="Green" price="1200.50" number="10" isAvailable="true"/>
                <product manufacturer="SHELLY" model="BH456" date="20-09-2019" color="Blue"  price="1200.60" number="0" isAvailable="false"/>
            </hardware>
        </bedroom>
        <livingRoom>
            <technique>
                <product manufacturer="SONY" model="CD567" date="19-08-2018" color="Red"   price="2100.10" number="0" isAvailable="false"/>
                <product manufacturer="SONY" model="CE567" date="18-08-2018" color="Green" price="2100.20" number="0" isAvailable="false"/>
                <product manufacturer="SONY" model="CF567" date="17-08-2018" color="Blue"  price="2100.30" number="0" isAvailable="false"/>
            </technique>
            <hardware>
                <product manufacturer="ATLANT" model="CG678" date="16-07-2018" color="Red"   price="2200.40" number="1" isAvailable="true"/>
                <product manufacturer="ATLANT" model="CH678" date="15-07-2018" color="Green" price="2200.50" number="2" isAvailable="true"/>
                <product manufacturer="ATLANT" model="CI678" date="14-07-2018" color="Blue"  price="2200.60" number="3" isAvailable="true"/>
            </hardware>
        </livingRoom>
    </categories>
</cs:shop>
